### ISSUE TITLE
Break statement causes "Cannot read property '0' of undefined"

### ISSUE THREAD

**Issue by vladidx** [lachrist/aran-access#1]
Hi Laurent,

aran-access is a very interesting project around JS access control systems. I tried to transform the following JS code (reduced to important aspects):

```
var fn = function(t, T) {
	switch(t) {
		case 1:
			switch(T) {
				case "a":
					return "1a";
			}
			break;
	}
	return "not found";
}
console.log(fn(1,"b"));
```

It gives me back the following error:
> Uncaught TypeError: Cannot read property '0' of undefined

![aran-access-error](https://user-images.githubusercontent.com/29225968/48970555-9f245680-f00d-11e8-83b5-3b04394fb67a.png)

Looks to me like a problem with the break statement in line 8.

Best regards
Vladi

**Comment by lachrist** [comment]
Thanks a lot for the bug report Vladislav :)
I will make sure to investigate it this week!

Kind Regards,
Laurent

On 24 Nov 2018, at 17:28, Vladislav Dexheimer <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Laurent,

aran-access is a very interesting project around JS access control systems. I tried to transform the following JS code (reduced to important aspects):

var fn = function(t, T) {
        switch(t) {
                case 1:
                        switch(T) {
                                case "a":
                                        return "1a";
                        }
                        break;
        }
        return "not found";
}
console.log(fn(1,"b"));


It gives me back the following error:

Uncaught TypeError: Cannot read property '0' of undefined

[aran-access-error]<https://user-images.githubusercontent.com/29225968/48970555-9f245680-f00d-11e8-83b5-3b04394fb67a.png>

Looks to me like a problem with the break statement in line 8.

Best regards
Vladi

**Comment by lachrist** [comment]
I moved this project back to its original repository: https://github.com/lachrist/linvail. You can open a new issue there if the problem persists.

Cheers,
Laurent
